# Generated by Django 4.1.4 on 2022-12-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Superuser"),
                    (2, "Staff"),
                    (3, "Consumer"),
                    (4, "Producer"),
                    (5, "Certifier"),
                ],
                default=3,
            ),
        ),
    ]
