# Generated by Django 4.1.4 on 2023-04-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_verificationcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worksin",
            name="role",
            field=models.CharField(
                choices=[
                    ("CA", "Company Admin"),
                    ("DS", "Domain Supervisor"),
                    ("DW", "Domain Worker"),
                    ("DE", "Dealer"),
                ],
                max_length=5,
            ),
        ),
    ]
