# Generated by Django 4.1.4 on 2023-04-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_alter_company_options_alter_establishment_options_and_more"),
        ("users", "0003_alter_worksin_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worksin",
            name="establishments_in_charge",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="workers",
                to="company.establishment",
            ),
        ),
    ]
