# Generated by Django 4.1.4 on 2023-12-27 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_worksin_role_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationcode",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_code",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
