# Generated by Django 4.1.4 on 2024-01-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_verificationcode_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="user_images/"),
        ),
    ]
