language: python
python:
  - "3.8"

services:
  - postgresql # Enable PostgreSQL database

env:
  global:
    - DJANGO_SETTINGS_MODULE="backend.settings"
    - PIP_CACHE_DIR=$HOME/.cache/pip
    - POETRY_VERSION=1.7.1

# Cache the Poetry installation
cache:
  directories:
    - $PIP_CACHE_DIR
    - $HOME/.cache/pypoetry

before_install:
  - pip install -U pip
  - pip install "poetry==$POETRY_VERSION"

install:
  - poetry install

before_script:
  - psql -c 'create database test_db;' -U postgres
  - poetry run python manage.py migrate --noinput

script:
  - poetry run pytest

branches:
  only:
    - main
