# Generated by Django 4.1.4 on 2023-09-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_parcel_album"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parcel",
            name="image",
        ),
    ]
