# Generated by Django 4.1.4 on 2024-01-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_remove_parcel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="polygon",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
