# Generated by Django 4.1.4 on 2023-08-27 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0002_history_lot_id_history_parcel_history_product_and_more"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={},
        ),
        migrations.AddField(
            model_name="review",
            name="scan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="history.historyscan",
            ),
        ),
    ]
