# Generated by Django 4.1.4 on 2023-04-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("finish_date", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField()),
                ("published", models.BooleanField(default=False)),
                ("earning", models.FloatField(default=0)),
                ("qr_code", models.ImageField(blank=True, upload_to="qr_codes")),
            ],
        ),
    ]
