# Generated by Django 4.1.4 on 2022-12-29 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("date", models.DateTimeField()),
                ("description", models.TextField()),
                ("published", models.BooleanField(default=False)),
                ("qr_code", models.ImageField(blank=True, upload_to="qr_codes")),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("image", models.ImageField(blank=True, upload_to="event_images")),
                ("certified", models.BooleanField(default=False)),
                ("index", models.IntegerField(default=0)),
                (
                    "history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="history.history",
                    ),
                ),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="product.parcel"
                    ),
                ),
            ],
        ),
    ]
