# Generated by Django 4.1.4 on 2023-04-11 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="parcel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="histories",
                to="product.parcel",
            ),
        ),
    ]
