# Generated by Django 4.1.4 on 2023-09-29 17:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0003_remove_parcel_image"),
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="lot_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="parcel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="histories",
                to="product.parcel",
            ),
        ),
        migrations.AddField(
            model_name="history",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="histories",
                to="product.product",
            ),
        ),
        migrations.AddField(
            model_name="history",
            name="production_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="history",
            name="reputation",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="history",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="WeatherEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("image", models.ImageField(blank=True, upload_to="event_images")),
                ("certified", models.BooleanField(default=False)),
                ("index", models.IntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FR", "Frost"),
                            ("DR", "Drought"),
                            ("HW", "Heat Wave"),
                            ("TS", "Tropical Storm"),
                            ("HW", "High Winds"),
                            ("HH", "High Humidity"),
                            ("LH", "Low Humidity"),
                        ],
                        max_length=2,
                    ),
                ),
                ("temperature", models.FloatField(default=0)),
                ("humidity", models.FloatField(default=0)),
                ("time_period", models.CharField(blank=True, max_length=30, null=True)),
                ("observation", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_events",
                        to="history.history",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("image", models.ImageField(blank=True, upload_to="event_images")),
                ("certified", models.BooleanField(default=False)),
                ("index", models.IntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PL", "Planting"),
                            ("HA", "Harvesting"),
                            ("IR", "Irrigation"),
                            ("PR", "Pruning"),
                        ],
                        max_length=2,
                    ),
                ),
                ("observation", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_events",
                        to="history.history",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoryScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.CharField(blank=True, max_length=30, null=True)),
                ("city", models.CharField(blank=True, max_length=30, null=True)),
                ("country", models.CharField(blank=True, max_length=30, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_scans",
                        to="history.history",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneralEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("image", models.ImageField(blank=True, upload_to="event_images")),
                ("certified", models.BooleanField(default=False)),
                ("index", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=90)),
                ("observation", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_events",
                        to="history.history",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChemicalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("image", models.ImageField(blank=True, upload_to="event_images")),
                ("certified", models.BooleanField(default=False)),
                ("index", models.IntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FE", "Fertilizer"),
                            ("PE", "Pesticide"),
                            ("FU", "Fungicide"),
                            ("HE", "Herbicide"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "commercial_name",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("volume", models.FloatField(default=0)),
                ("concentration", models.FloatField(default=0)),
                ("area", models.FloatField(blank=True, default=0, null=True)),
                (
                    "way_of_application",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("time_period", models.CharField(blank=True, max_length=30, null=True)),
                ("observation", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_events",
                        to="history.history",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
