# Generated by Django 4.1.4 on 2023-04-11 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("history", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("image", models.ImageField(blank=True, upload_to="event_images")),
                ("certified", models.BooleanField(default=False)),
                ("index", models.IntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FR", "Frost"),
                            ("DR", "Drought"),
                            ("HW", "Heat Wave"),
                            ("TS", "Tropical Storm"),
                            ("HW", "High Winds"),
                            ("HH", "High Humidity"),
                            ("LH", "Low Humidity"),
                        ],
                        max_length=2,
                    ),
                ),
                ("temperature", models.FloatField(default=0)),
                ("humidity", models.FloatField(default=0)),
                ("time_period", models.CharField(blank=True, max_length=30, null=True)),
                ("observation", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="history.history",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GeneralEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("image", models.ImageField(blank=True, upload_to="event_images")),
                ("certified", models.BooleanField(default=False)),
                ("index", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=90)),
                ("observation", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="history.history",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChemicalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("image", models.ImageField(blank=True, upload_to="event_images")),
                ("certified", models.BooleanField(default=False)),
                ("index", models.IntegerField(default=0)),
                ("type", models.CharField(max_length=30)),
                ("volume", models.FloatField(default=0)),
                ("concentration", models.FloatField(default=0)),
                ("time_period", models.CharField(blank=True, max_length=30, null=True)),
                ("observation", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="history.history",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
