# Generated by Django 4.1.4 on 2023-10-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0002_history_lot_id_history_parcel_history_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="published",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
