# Generated by Django 4.1.4 on 2023-04-12 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0003_weatherevent_generalevent_chemicalevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chemicalevent",
            name="history",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_events",
                to="history.history",
            ),
        ),
        migrations.AlterField(
            model_name="generalevent",
            name="history",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_events",
                to="history.history",
            ),
        ),
        migrations.AlterField(
            model_name="weatherevent",
            name="history",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_events",
                to="history.history",
            ),
        ),
    ]
