# Generated by Django 4.1.4 on 2024-01-15 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("history", "0004_remove_weatherevent_humidity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chemicalevent",
            name="image",
        ),
        migrations.RemoveField(
            model_name="generalevent",
            name="image",
        ),
        migrations.RemoveField(
            model_name="productionevent",
            name="image",
        ),
        migrations.RemoveField(
            model_name="weatherevent",
            name="image",
        ),
        migrations.AddField(
            model_name="chemicalevent",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.gallery",
            ),
        ),
        migrations.AddField(
            model_name="generalevent",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.gallery",
            ),
        ),
        migrations.AddField(
            model_name="productionevent",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.gallery",
            ),
        ),
        migrations.AddField(
            model_name="weatherevent",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.gallery",
            ),
        ),
    ]
