# Generated by Django 4.1.4 on 2023-04-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0004_alter_chemicalevent_history_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="description",
        ),
        migrations.AddField(
            model_name="history",
            name="lot_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="observation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="production_amount",
            field=models.FloatField(default=0),
        ),
    ]
