# Generated by Django 4.1.4 on 2024-01-16 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        (
            "history",
            "0005_remove_chemicalevent_image_remove_generalevent_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.gallery",
            ),
        ),
    ]
