# Generated by Django 4.1.4 on 2023-08-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0006_historyscan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historyscan",
            name="ip",
        ),
        migrations.AddField(
            model_name="historyscan",
            name="ip_address",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
