# Generated by Django 4.1.4 on 2025-02-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0006_history_album"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chemicalevent",
            name="area",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="chemicalevent",
            name="concentration",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="chemicalevent",
            name="time_period",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="chemicalevent",
            name="volume",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="chemicalevent",
            name="way_of_application",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
