# Generated by Django 4.1.4 on 2023-08-03 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
        ("history", "0007_remove_historyscan_ip_historyscan_ip_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="history",
            old_name="observation",
            new_name="description",
        ),
        migrations.AddField(
            model_name="history",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="histories",
                to="product.product",
            ),
        ),
    ]
