# Generated by Django 4.1.4 on 2023-09-06 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("history", "0010_historyscan_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("image", models.ImageField(blank=True, upload_to="event_images")),
                ("certified", models.BooleanField(default=False)),
                ("index", models.IntegerField(default=0)),
                ("type", models.CharField(max_length=30)),
                ("observation", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_events",
                        to="history.history",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
