# Generated by Django 4.1.4 on 2023-09-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0011_productionevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemicalevent",
            name="area",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="chemicalevent",
            name="commercial_name",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="chemicalevent",
            name="way_of_application",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
