# Generated by Django 4.1.4 on 2023-09-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0013_remove_chemicalevent_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chemicalevent",
            name="type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
