# Generated by Django 4.1.4 on 2023-09-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0014_alter_chemicalevent_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chemicalevent",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FE", "Fertilizer"),
                    ("PE", "Pesticide"),
                    ("FU", "Fungicide"),
                    ("HE", "Herbicide"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productionevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("PL", "Planting"),
                    ("HA", "Harvesting"),
                    ("IR", "Irrigation"),
                    ("PR", "Pruning"),
                ],
                max_length=2,
            ),
        ),
    ]
