# Generated by Django 4.1.4 on 2022-12-29 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("tradename", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=30)),
                ("fiscal_id", models.CharField(help_text="RUT", max_length=30)),
                ("logo", models.ImageField(blank=True, upload_to="company_logos")),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Establishment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=30)),
                ("city", models.CharField(blank=True, max_length=30, null=True)),
                ("zone", models.CharField(blank=True, max_length=30, null=True)),
                ("state", models.CharField(max_length=30)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="establishment_images"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
            ],
        ),
    ]
