# Generated by Django 4.1.4 on 2023-09-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Company", "verbose_name_plural": "Companies"},
        ),
        migrations.AlterModelOptions(
            name="establishment",
            options={
                "verbose_name": "Establishment",
                "verbose_name_plural": "Establishments",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="invitation_code",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="establishment",
            name="country",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="establishment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="fiscal_id",
            field=models.CharField(
                blank=True, help_text="RUT", max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="tradename",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
