# Generated by Django 4.1.4 on 2023-03-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_company_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="establishment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
