# Generated by Django 4.1.4 on 2023-10-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_company_options_alter_establishment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="country",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
