# Generated by Django 4.1.4 on 2023-04-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_establishment_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="invitation_code",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="fiscal_id",
            field=models.CharField(
                blank=True, help_text="RUT", max_length=30, null=True
            ),
        ),
    ]
