# Generated by Django 4.1.4 on 2023-10-13 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("company", "0003_alter_company_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="establishment",
            name="image",
        ),
        migrations.AddField(
            model_name="establishment",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.gallery",
            ),
        ),
    ]
