# Generated by Django 4.1.4 on 2023-04-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_company_invitation_code_alter_company_fiscal_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="tradename",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
