# Generated by Django 4.1.4 on 2023-07-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_alter_company_tradename"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Company", "verbose_name_plural": "Companies"},
        ),
        migrations.AlterModelOptions(
            name="establishment",
            options={
                "verbose_name": "Establishment",
                "verbose_name_plural": "Establishments",
            },
        ),
        migrations.AddField(
            model_name="establishment",
            name="country",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
