name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: postgres:latest
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres is ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.1

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install

      - name: Run migrations
        run: |
          poetry run python manage.py migrate

      - name: Run tests
        run: |
          poetry run python manage.py test

    env:
      DJANGO_SETTINGS_MODULE: backend.settings
      SECRET_KEY: "django-insecure-x:yv-0g&cajngn8rte!cc(!@%-2uc_ds($#(j4a-vab1zxn_5"
      DATABASE_NAME: "test_db"
      DATABASE_USER: "omunoz"
      DATABASE_PASSWORD: "om123456"
      DATABASE_HOST: "localhost"
      DATABASE_PORT: "5432"
      ALLOWED_HOSTS: "*"
      DEBUG: True
      CSRF_TRUSTED_ORIGINS:
        ["http://app.localhost:3000", "http://localhost:3000"]
      BASE_TRACEIT_URL: http://localhost:3000/
      BASE_APP_URL: http://app.localhost:3000/
      EMAIL_HOST: "smtp.sendgrid.net"
      SENDGRID_API_KEY: "key"
      FROM_EMAIL_ADDRESS: info@traceit.io
